### ISSUE TITLE
Add example of initializing a new project from scratch

### ISSUE THREAD

**Issue by blargg** [Gabriel439/haskell-nix#70]
One thing that seems to be missing is a method to initialize a project from an empty directory.
So far, we have project folders with *.nix files in them already. There's no instruction about the best way to create a new project from scratch.

For example, we might suggest the following

> Open a nix shell with ghc and cabal. Give the command for this.
> Initialize the cabal info. Cabal init command
> Generate the *.nix files. Probably use cabal2nix, and write the release.nix file

**Comment by Gabriel439** [comment]
@blargg: So there is an easy way to do this if you only plan to do one-off development for a single project.  You can use:

```bash
$ cabal2nix --shell . > shell.nix
```

... and then `nix-shell` should "just work".  However, that's sort of out of scope for this guide, which is more about how to scale beyond one project and how to do more sophisticated dependency management.  This guide assumes that you're willing to do some up-front work because your needs are more complex.

However, the simpler use cases you might have in mind are covered by the Haskell section of the Nixpkgs manual:

https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure

**Comment by blargg** [comment]
I think my initial suggestion can be split into these two parts.

1. With the current setup described in the README, there is no way to `cabal init` a new project. I will fail since there is no ghc installed. I was curious if people would either install the compiler on the system, or use nix-shell with ghc to initialize the project.

Adding info about project initialization is nice to have and fits with the theme of Project 0. If you are learning the basics of nix/haskell, like when you are reading Project 0 or Project 1, making a simple project to hack on to try things out can be useful.
It seems strange to leave out a detail about project initialization just because the focus is larger projects. Large projects get initialized at some point, too.

2. I think the tutorial would be easier to understand if it starts at the initial state of the project. For Project 0, this would be just the *.cabal, *.hs, LICENCE and README.md. The tutorial would then have instructions to write or generate the *.nix files. The last instruction is that this should match the final state in Project 1 (or some other name) so the reader can verify their work.

This suggestion is a matter of preference, I'm fine dropping that suggestion if few people think it's helpful.

**Comment by blargg** [comment]
Thanks, looks good.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
