### ISSUE TITLE
Error: file 'nixpkgs' was not found in the Nix search path

### ISSUE THREAD

**Issue by 1930s** [Gabriel439/haskell-nix#73]
Hi,

After I ran `nix-build release0.nix`, it shows `error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at /Users/allen/haskell-nix/project0/release0.nix:2:17`

What should I do next? Thank you.

**Comment by Gabriel439** [comment]
@1930s: What output do you get when you run the following command?

```bash
$ echo "${NIX_PATH}"

**Comment by 1930s** [comment]
@Gabriel439 Nothing. 

![screen shot 2019-01-12 at 12 12 53 pm](https://user-images.githubusercontent.com/33078987/51069091-50855700-1663-11e9-9ea0-d8055de98753.png)

**Comment by Gabriel439** [comment]
@1930s: Then it looks like you have some misconfiguration in your local Nix installation.  Usually when you install Nix the installer asks you to add some line like this to your `~/.profile`:

```bash
. ~/.nix-profile/etc/profile.d/nix.sh
```

... so that when you log into your shell all of the necessary environment variables have been set.  Could you check if you have that setup script added as a login script?

**Comment by 1930s** [comment]
Thank you so much @Gabriel439, problem solved!

**Comment by Gabriel439** [comment]
You're welcome! 🙂
