### ISSUE TITLE
Error builing `project1`/`release1`

### ISSUE THREAD

**Issue by vyorkin** [Gabriel439/haskell-nix#74]
Hello, Gabriel! Thanks for your work on this guide!
I'm just starting with Nix + Haskell, so chances are I might be doing smth wrong.

While reading and trying out examples, I noticed that I can't build the `project1`/`relase1`:

```
haskell-nix/project1 [master●] » nix-build --attr project1.nix release1.nix
error: attribute 'nix' in selection path 'project1.nix' not found
```

**Comment by Gabriel439** [comment]
@vyorkin: Replace `project1.nix` in your command with just `project1` and then I believe the command should work.

To explain what is going on: if you tell the `nix-build` command to build a file (like `release1.nix`) and if that file contains a record of things to build, then you can tell `nix-build` which field of that record to build using the `--attr` command line option.  The argument you pass to the `--attr` option is the name of the field that you want to build.  In this case, the record stored inside `release1.nix` contains one field named `project1` so the full option is `--attr project1`.  In this case `project1` is the name of a field and not the name of a file, which is why there is no `.nix` suffix for `project1`.

**Comment by vyorkin** [comment]
Thanks for such a detailed explanation (and sorry for my innatention & ignorance)

**Comment by Gabriel439** [comment]
You're welcome! 🙂
